"""empty message

Revision ID: 7d5c203fdc6e
Revises: 2af54de08b4e
Create Date: 2023-08-15 15:27:07.570680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5c203fdc6e'
down_revision = '2af54de08b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('counter', sa.Integer(), nullable=True))
    op.add_column('link', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('link', sa.Column('OperatingSystem', sa.String(), nullable=True))
    op.drop_column('link', 'isVisited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('isVisited', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('link', 'OperatingSystem')
    op.drop_column('link', 'browser')
    op.drop_column('link', 'counter')
    # ### end Alembic commands ###
