"""empty message

Revision ID: 8642000ba4a6
Revises: 324312893756
Create Date: 2023-08-16 09:32:34.646145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642000ba4a6'
down_revision = '324312893756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('shorten_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'link', ['shorten_url'])
    op.drop_column('link', 'generatedCode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('generatedCode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'link', type_='unique')
    op.drop_column('link', 'shorten_url')
    # ### end Alembic commands ###
