"""empty message

Revision ID: d757b34da03d
Revises: 1badeec51699
Create Date: 2023-08-21 15:53:19.201061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd757b34da03d'
down_revision = '1badeec51699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('private_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'link', ['private_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='unique')
    op.drop_column('link', 'private_key')
    # ### end Alembic commands ###
