"""empty message

Revision ID: ff7723919d90
Revises: 8642000ba4a6
Create Date: 2023-08-16 10:01:43.839117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff7723919d90'
down_revision = '8642000ba4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('key', sa.String(), nullable=True))
    op.add_column('link', sa.Column('extra_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('link_shorten_url_key', 'link', type_='unique')
    op.create_unique_constraint(None, 'link', ['key'])
    op.drop_column('link', 'device')
    op.drop_column('link', 'browser')
    op.drop_column('link', 'operatingSystem')
    op.drop_column('link', 'shorten_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('shorten_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('link', sa.Column('operatingSystem', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('link', sa.Column('browser', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('link', sa.Column('device', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'link', type_='unique')
    op.create_unique_constraint('link_shorten_url_key', 'link', ['shorten_url'])
    op.drop_column('link', 'extra_information')
    op.drop_column('link', 'key')
    # ### end Alembic commands ###
